// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var Food;
    return Food = (function() {

      function Food(map, color) {
        this.map = map;
        this.color = color;
        this.spawn();
      }

      Food.prototype.spawn = function() {
        var pt, _i, _len, _ref, _results;
        this.x = ~~(Math.random() * this.map.width);
        this.y = ~~(Math.random() * this.map.height);
        if (!this.map.pts) {
          return;
        }
        _ref = this.map.pts;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          pt = _ref[_i];
          if (pt.x === this.x && pt.y === this.y) {
            _results.push(this.spawn());
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };

      Food.prototype.draw = function() {
        return this.map.drawCell(this.x, this.y, this.color);
      };

      return Food;

    })();
  });

}).call(this);
