// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var Food;
    return Food = (function() {

      function Food(map, color) {
        this.map = map;
        this.color = color;
        this.spawn();
      }

      Food.prototype.spawn = function() {
        this.x = ~~(Math.random() * this.map.width);
        return this.y = ~~(Math.random() * this.map.height);
      };

      Food.prototype.draw = function() {
        return this.map.drawCell(this.x, this.y, this.color);
      };

      return Food;

    })();
  });

}).call(this);
