// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var Map;
    return Map = (function() {

      function Map(ctx, cw, type) {
        this.ctx = ctx;
        this.cw = cw;
        this.width = this.ctx.width / this.cw;
        this.height = this.ctx.height / this.cw;
        this.type = type != null ? type : 'square';
      }

      Map.prototype.drawCell = function(x, y, color, alpha, type) {
        var r;
        this.ctx.fillStyle = color != null ? color : 'white';
        this.ctx.globalAlpha = alpha;
        if (type == null) {
          type = this.type;
        }
        switch (type) {
          case 'square':
            this.ctx.fillRect(x * this.cw, y * this.cw, this.cw, this.cw);
            this.ctx.fillStyle = 'white';
            break;
          case 'circle':
            r = this.cw >> 1;
            this.ctx.beginPath();
            this.ctx.arc(x * this.cw + r, y * this.cw + r, r, 0, Math.PI * 2, true);
            this.ctx.closePath();
            this.ctx.fill();
        }
        return this.ctx.globalAlpha = 1;
      };

      Map.prototype.clear = function() {
        this.ctx.fillStyle = 'black';
        this.ctx.fillRect(0, 0, this.ctx.width, this.ctx.height);
        return this.ctx.fillStyle = 'white';
      };

      return Map;

    })();
  });

}).call(this);
