// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var createContext;
    return createContext = function(parent, width, height) {
      var canvas, ctx;
      canvas = document.createElement('canvas');
      ctx = canvas.getContext('2d');
      canvas.width = width != null ? width : window.innerWidth;
      canvas.height = height != null ? height : window.innerHeight;
      document.querySelector(parent != null ? parent : 'body').appendChild(canvas);
      ctx.width = canvas.width;
      ctx.height = canvas.height;
      return ctx;
    };
  });

}).call(this);
